# Generated by Django 6.1.1 on 2026-09-05 15:30

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_room_code, max_length=6, unique=True)),
                ('state', models.CharField(choices=[('waiting', 'Waiting for players'), ('playing', 'Game in progress'), ('finished', 'Game over')], default='waiting', max_length=20)),
                ('deck', models.JSONField(default=list)),
                ('discard_pile', models.JSONField(default=list)),
                ('current_turn_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('carrot_0', models.JSONField(blank=True, null=True)),
                ('carrot_1', models.JSONField(blank=True, null=True)),
                ('carrot_2', models.JSONField(blank=True, null=True)),
                ('carrot_3', models.JSONField(blank=True, null=True)),
                ('visible_0', models.BooleanField(default=False)),
                ('visible_1', models.BooleanField(default=False)),
                ('visible_2', models.BooleanField(default=False)),
                ('visible_3', models.BooleanField(default=False)),
                ('hand', models.JSONField(default=list)),
                ('is_ready', models.BooleanField(default=False)),
                ('has_claimed_cooked', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room')),
            ],
            options={
                'unique_together': {('room', 'position')},
            },
        ),
    ]
